package bastion

var SpecialFacilities = []SpecialFacility{
	SpecialFacility{
		Level:        5,
		Name:         "Arcane Study",
		Prerequisite: "Ability to use an Arcane Focus or a tool as a Spellcasting Focus",
		Order:        "Craft",
	},
	SpecialFacility{
		Level:        5,
		Name:         "Armory  ",
		Prerequisite: "None",
		Order:        "Trade",
	},
	SpecialFacility{
		Level:        5,
		Name:         "Barrack",
		Prerequisite: "None",
		Order:        "Recruit",
	},
	SpecialFacility{
		Level:        5,
		Name:         "Garden",
		Prerequisite: "None",
		Order:        "Harvest",
	},
	SpecialFacility{
		Level:        5,
		Name:         "Library",
		Prerequisite: "None",
		Order:        "Research",
	},
	SpecialFacility{
		Level:        5,
		Name:         "Sanctuary",
		Prerequisite: "Ability to use a Holy Symbol or Druidic Focus as a Spellcasting Focus",
		Order:        "Craft",
	},
	SpecialFacility{
		Level:        5,
		Name:         "Smithy",
		Prerequisite: "None",
		Order:        "Craft",
	},
	SpecialFacility{
		Level:        5,
		Name:         "Storehouse",
		Prerequisite: "None",
		Order:        "Trade",
	},
	SpecialFacility{
		Level:        5,
		Name:         "Workshop",
		Prerequisite: "None",
		Order:        "Craft",
	},
	SpecialFacility{
		Level:        9,
		Name:         "Gaming Hall",
		Prerequisite: "None",
		Order:        "Trade",
	},
	SpecialFacility{
		Level:        9,
		Name:         "Greenhouse",
		Prerequisite: "None",
		Order:        "Harvest",
	},
	SpecialFacility{
		Level:        9,
		Name:         "Laboratory",
		Prerequisite: "None*",
		Order:        "Craft",
	},
	SpecialFacility{
		Level:        9,
		Name:         "Sacristy",
		Prerequisite: "Ability to use a Holy Symbol or Druidic Focus as a Spellcasting Focus",
		Order:        "Craft",
	},
	SpecialFacility{
		Level:        9,
		Name:         "Scriptorium",
		Prerequisite: "None*",
		Order:        "Craft",
	},
	SpecialFacility{
		Level:        9,
		Name:         "Stable",
		Prerequisite: "None",
		Order:        "Trade",
	},
	SpecialFacility{
		Level:        9,
		Name:         "Teleportation Circle",
		Prerequisite: "None",
		Order:        "Recruit",
	},
	SpecialFacility{
		Level:        9,
		Name:         "Theater",
		Prerequisite: "None",
		Order:        "Empower",
	},
	SpecialFacility{
		Level:        9,
		Name:         "Training Area",
		Prerequisite: "None",
		Order:        "Empower",
	},
	SpecialFacility{
		Level:        9,
		Name:         "Trophy Room",
		Prerequisite: "None",
		Order:        "Research",
	},
	SpecialFacility{
		Level:        13,
		Name:         "Archive",
		Prerequisite: "None",
		Order:        "Research",
	},
	SpecialFacility{
		Level:        13,
		Name:         "Meditation Cha,mber",
		Prerequisite: "None",
		Order:        "Empower",
	},
	SpecialFacility{
		Level:        13,
		Name:         "Menagerie",
		Prerequisite: "None",
		Order:        "Recruit",
	},
	SpecialFacility{
		Level:        13,
		Name:         "Observatory",
		Prerequisite: "Ability to use a Spellcasting Focus",
		Order:        "Empower",
	},
	SpecialFacility{
		Level:        13,
		Name:         "Pub",
		Prerequisite: "None",
		Order:        "Research",
	},
	SpecialFacility{
		Level:        13,
		Name:         "Reliquary",
		Prerequisite: "Ability to use a Holy Symbol or Druidic Focus as a Spellcasting Focus",
		Order:        "Harvest",
	},
	SpecialFacility{
		Level:        17,
		Name:         "Demiplane",
		Prerequisite: "Ability to use an Arcane Focus or a tool as a Spellcasting Focus",
		Order:        "Empower",
	},
	SpecialFacility{
		Level:        17,
		Name:         "Guildhall",
		Prerequisite: "Expertise in a skill",
		Order:        "Recruit",
	},
	SpecialFacility{
		Level:        17,
		Name:         "Sanctum",
		Prerequisite: "Ability to use a Holy Symbol or Druidic Focus as a Spellcasting Focus",
		Order:        "Empower",
	},
	SpecialFacility{
		Level:        17,
		Name:         "War Room",
		Prerequisite: "Fighting Style feature or Unarmored Defense feature",
		Order:        "Recruit",
	},
}
